trueSite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    
]

trueSite/trueSite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from mathpage.sitemaps import MathSitemap
from metodics.sitemaps import MetodSitemap
from School.sitemaps import SchoolSitemap
from blog.sitemaps import PostSitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import homepage.views

sitemaps1 = {
    'mathpage': MathSitemap,
}

sitemaps2 = {
    'metodics': MetodSitemap,
}

sitemaps3 = {
    'School': SchoolSitemap,
}

sitemaps4 = {
    'blog': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage.views.Home, name='Home'),
    path('math/', include('mathpage.urls'), name='math'),
    path('homework/', include('homework.urls')),
    path('School/', include('School.urls'), name='school'),
    path('metodics/', include('metodics.urls')),
    path('students/', include('students_works.urls')),
    path('blog/', include('blog.urls')),
    path('math/sitemap.xml', sitemap, {'sitemaps': sitemaps1},
    name='django.contrib.sitemaps.views.sitemap'),
    path('metodics/sitemap.xml', sitemap, {'sitemaps': sitemaps2},
    name='django.contrib.sitemaps.views.sitemap'),
    path('School/sitemap.xml', sitemap, {'sitemaps': sitemaps3},
    name='django.contrib.sitemaps.views.sitemap'),
    path('blog/sitemap.xml', sitemap, {'sitemaps': sitemaps4},
    name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trueSite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from trueSite.settings import ALLOWED_HOSTS

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                        self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique_for_date='publish')

    body = models.TextField()
    image = models.FileField(blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                                choices = STATUS_CHOICES,
                                default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                                self.publish.month,
                                self.publish.day,
                                self.slug])

    def get_full_url(self):
        domain = ALLOWED_HOSTS[1]
        return 'https://{domain}{path}'.format(domain=domain,path=self.get_absolute_url())

    def little_part_of_post(self):
        return " ".join(self.body.split()[:20]) + "..."
        
    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title

class PostImages(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='blog_images/')

    def __str__(self):
        return self.post.title

class SocialShares(models.Model):
    name = models.CharField(max_length=200)
    icon = models.ImageField(upload_to='icons/', blank=True, null=True)
    share_source = models.URLField()

    def name_cap(self):
        return str(self.name).title()
    
    def link_name(self):
        return str(self.name).lower()

trueSite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, PostImages
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count

def post_list(request, tag_slug=None):
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    paginator = Paginator(posts, 10)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')

        posts = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'blog/post/list_ajax.html', context={'posts': posts,
                                                                    'tag': tag})
    
    return render(request, 'blog/post/list.html', context={'posts': posts,
                                                            'tag': tag})

def post_detail(request, year, month, day, post):
    post_all = get_object_or_404(Post, slug=post,
                                    status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    images = PostImages.objects.filter(post=post_all)
    str_images_pathes = "~^"
    for i in images:
        str_images_pathes += str(i.images.url) + ","

    post_tags_ids = post_all.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post_all.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', context={'post': post_all,
                                                    'images': str_images_pathes,
                                                    'similar_posts':similar_posts,})

trueSite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<script src="{% static 'js/blogscript.js' %}">
</script>

<h1>{{ post.title }}</h1>
<p class="tags">
  Tags: 
  {% for tag in post.tags.all %}
  <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
      {{ tag.name }}
  </a>
  {% if not forloop.last %}, {% endif %}
  {% endfor %}
</p>
<div id="content-pictures">
  <p class="date">
    Published {{ post.publish }}
</p>
<script>
  var text = "{{ post.body|linebreaks }} {{ images }}";
  textWithPictures(text);
</script>
</div>
{% social_sharing post.get_full_url post.title %}
<hr class="separator-similar">
<h2>Похожие публикации</h2>
{% for post in similar_posts %}
  <p class="similar">
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </p>
  {% empty %}
  Нет похожих публикаций 
{% endfor %}

{% endblock %}

trueSite/blog/templates/blog/post/latest_posts.html
<ul style="padding: 0;">
    {% for post in latest_posts %}
    <li >
    <a class="recently-added" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

trueSite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}Блог{% endblock %}
{% block content %}
<h1>
    Собрание мыслей (блог)
</h1>
{% if tag %}
<h2>Посты с меткой "{{ tag.name }}"</h2>
{% endif %}
{% include "blog/post/list_ajax.html" %}
{% endblock %}
{% block domready %}  
var page = 1;  
var empty_page = false;  
var block_request = false;  
$(window).scroll(function() 
{    
    var margin = $(document).height() - $(window).height() - 200;    
    if($(window).scrollTop() > margin && empty_page == false &&  block_request == false) 
    {     
        block_request = true;      
        page += 1;     
        $.get('?page=' + page, 
        function(data) {        
            if(data == '') {          
                empty_page = true;        
            }        
            else {          
                block_request = false;          
                $('#content').append(data);        
            }      
        });    
    }  
});
{% endblock %}

trueSite/blog/templates/blog/post/list_ajax.html
{% for post in posts %}
<h2>
    <a class="main" href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
    <p class="tags">
        Tags: 
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
</h2>
<p class="date">
    Published {{ post.publish }}
</p>
   {{ post.little_part_of_post }} 
{% endfor %}

trueSite/blog/templates/blog/post/social_share.html
<ul>
    {% for link in social_share %}
    <a class="sharing-button__link" href="{{ link.share_source }}" 
        onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=400,width=500');
        return false;"
        target="_blank" rel="nofollow">
        <div class="sharing-button sharing-button--{{ link.link_name }} sharing-button--medium">
            <div aria-hidden="true" class="sharing-button__icon sharing-button__icon--solid">
            {% if link.icon %}
                <img src="{{ link.icon.url }}">
            {% endif %}
                </div>Поделиться в {{ link.name_cap  }}</div>
        </a>
    {% endfor %}
</ul>