trueSite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    
]

trueSite/metodics/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.metod, name="metod"),
    path('search/', views.metod_search, name='metod_search'),
    
]

trueSite/trueSite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from mathpage.sitemaps import MathSitemap
from metodics.sitemaps import MetodSitemap
from School.sitemaps import SchoolSitemap
from blog.sitemaps import PostSitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import homepage.views

sitemaps1 = {
    'mathpage': MathSitemap,
}

sitemaps2 = {
    'metodics': MetodSitemap,
}

sitemaps3 = {
    'School': SchoolSitemap,
}

sitemaps4 = {
    'blog': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage.views.Home, name='Home'),
    path('math/', include('mathpage.urls'), name='math'),
    path('homework/', include('homework.urls')),
    path('School/', include('School.urls'), name='school'),
    path('metodics/', include('metodics.urls')),
    path('students/', include('students_works.urls')),
    path('blog/', include('blog.urls')),
    path('math/sitemap.xml', sitemap, {'sitemaps': sitemaps1},
    name='django.contrib.sitemaps.views.sitemap'),
    path('metodics/sitemap.xml', sitemap, {'sitemaps': sitemaps2},
    name='django.contrib.sitemaps.views.sitemap'),
    path('School/sitemap.xml', sitemap, {'sitemaps': sitemaps3},
    name='django.contrib.sitemaps.views.sitemap'),
    path('blog/sitemap.xml', sitemap, {'sitemaps': sitemaps4},
    name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trueSite/metodics/models.py
from django.db import models



class MetodPage(models.Model):
    title = models.TextField(max_length=300)
    text_file = models.FileField(upload_to='metod/')
    objects = models.Manager()
    description = models.ImageField(blank=True, null=True, upload_to='metod_images/')
    video_source = models.URLField(blank=True, null=True)


    def __str__(self):
        return self.title

trueSite/metodics/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()
    

trueSite/metodics/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import MetodPage
from .forms import SearchForm
from django.contrib.postgres.search import TrigramSimilarity

def metod(request):
    metods = MetodPage.objects.all().order_by('title')
    paginator = Paginator(metods, 10)
    page = request.GET.get('page')
    try:
        metod = paginator.page(page)
    except PageNotAnInteger:
        metod = paginator.page(1)
    except EmptyPage:
        metod = paginator.page(paginator.num_pages)
    return render(request, 'metodics/metod.html', {'page': page, 'metods': metod})


def metod_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = MetodPage.objects.annotate(similarity=TrigramSimilarity('title', query),).filter(similarity__gt=0.1).order_by('-similarity').order_by('title')

    return render(request, 'metodics/search.html',
                    {'form': form,
                    'query': query,
                    'results':results})

trueSite/metodics/templates/metodics/metod.html
<html lang="ru"><head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Лекции, способы решения задач, подготовка к экзаменам и контрольным работам по дисциплине ЕН.01 'Математика'.">
    <meta name="author" content="">
  
    <title>Справочные материалы</title>
  <!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
  m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
  (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

  ym(71442256, "init", {
       clickmap:true,
       trackLinks:true,
       accurateTrackBounce:true,
       webvisor:true
  });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/71442256" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

  
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css">
  
    <!-- Plugin CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-creative/5.1.8/css/creative.css" type="text/css" rel="stylesheet">
  
    <!-- Theme CSS - Includes Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-creative/5.1.8/css/creative.min.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177055652-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-177055652-1');
</script>

  </head>
  
  {% load static %}
  <body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark" style="padding: 0 5vw;" id="mainNav">
      <div class="container text-white">
        <a class="navbar-brand js-scroll-trigger text-white" href="{% url 'Home' %}">Главная</a>
        <form action="{% url 'metod_search' %}" method="GET" style="padding-top: 2vh;"> 
          <input type="text" name="query" required="" id="id_query" placeholder="Search...">    
          <input type="submit" value="Поиск"> 
          </form>
        
      </div>
    </nav>

   <!-- Portfolio Section -->
    <section class="page-section bg-white" id="portfolio">
        <br/>
        <div class="container" style="max-width: 90vh; text-align: center;">
         {% block content %}

        {% for m in metods %}
        <h3 style="color: black;">{{ m.title }}</h3>
        {% if m.description %}
        <p>
          <img src="{{ m.description.url }}" style="width: 45vh; height: 40vh;">
        </p>
        {% endif %}
        <br/>
        <button style="align-items: center;"><a href = '{{ m.text_file.url }}'>
          Скачать
        </a></button>
        <br/>
        {% if m.video_source %}
           {% load embed_video_tags %}
            <p style="padding-top: 2vh; padding-bottom: 5vh; display: flex; align-items: center; max-width: 99vw;">
              <div style="text-align: center; max-width: 99vw;">
                {% video m.video_source "100% x 50%" %}
              </div>
            </p>
           <br/>
           {% endif %}
          <hr/>
        {% endfor %}
        <div style="display: flex; align-items: center; justify-content: center; padding: 5px;">
        {% include 'paginator.html' with page=metods %}
        </div>
        {% endblock %}
        </div>
        
     </section>     

  
    <!-- Footer -->
    <footer class="bg-light py-5">
      <div class="container" style="width: 100%;">
        <div class="small text-center text-muted">Copyright © Alexandra Gridneva 2020-{% now "Y" %}</div>
      </div>
    </footer>
  
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


  
  </body>
  </html>

trueSite/metodics/templates/metodics/search.html
<html lang="ru"><head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  
    <title>Справочные материалы</title>
  <!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
  m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
  (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

  ym(71442256, "init", {
       clickmap:true,
       trackLinks:true,
       accurateTrackBounce:true,
       webvisor:true
  });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/71442256" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
  
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css">
  
    <!-- Plugin CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-creative/5.1.8/css/creative.css" type="text/css" rel="stylesheet">
  
    <!-- Theme CSS - Includes Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-creative/5.1.8/css/creative.min.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177055652-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-177055652-1');
</script>


  </head>
  
  {% load static %}
  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark" style="padding: 0 5vw;" id="mainNav">
      <div class="container text-white">
        <a class="navbar-brand js-scroll-trigger text-white" href="{% url 'Home' %}">Главная</a>
        <form action="{% url 'metod_search' %}" method="GET" style="padding-top: 2vh;"> 
        <input type="text"name="query" required="" id="id_query" placeholder="Search...">    
        <input type="submit" value="Поиск"> 
        </form>
        </div>
    </nav>

    <section class="page-section bg-white" id="portfolio">
        <br/>
        <div class="container" style="max-width: 90vh; text-align: center;">
    {% block content %}  
    {% if query %}    
    <h1>Материалы с ключевым словом "{{ query }}"</h1> 
       <h3>{% with results.count as total_results %}
            Всего найдено: {{ total_results }}     
            {% endwith %}
        </h3>{% for post in results %}      
    <h3>{{ post.title }}

    </h3>
    {% if post.description %} 
    <p>
      <img src="{{ post.description.url }}" style="width: 45vh; height: 40vh;">
    </p>
    {% endif %}
    <br/>
    <button style="align-items: center;"><a href = '{{ post.text_file.url }}'>
      Скачать
    </a></button> 
    <hr/>
        <br/>
        {% if post.video_source != null %}
           {% load embed_video_tags %}
            <p style="padding-top: 2vh; padding-bottom: 5vh; display: flex; align-items: center;">
              <div style="text-align: center;">
                {% video post.video_source "small" %}
              </div>
            </p>
           <br/>
           {% endif %}
    {% empty %}
    <p>Результатов не найдено.</p>    
    {% endfor %}
    {% endif %}
    {% endblock %}

    </div>
        
</section> 
    <!-- Footer -->
    <footer class="bg-light py-5">
      <div class="container" style="width: 100%;">
        <div class="small text-center text-muted">Copyright © Alexandra Gridneva {% now "Y" %}</div>
      </div>
    </footer>
  
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  
  
  </body></html>